version: "3.5"

services:
  database:
    container_name: taskill_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5454:5432"

  taskill-api:
    image: taskill
    ports:
      - "5000:80"
    depends_on:
      - "database"

volumes:
  postgres-db:
    driver: local
